In [ ]:
Numpy Array
=> to make computation efficient
=>homogeneous collection 

In [1]:
#cube sodyo bhane k garne

In [2]:
import numpy as np

In [3]:
#broadcasting
x = np.array([5,4,6,1]) 
y =np.array([2,1,3,4])

z = x+2
print(z)

[7 6 8 3]


In [ ]:
#broadcasting
[5,4,6,1]+[2,2,2,2,] garchhaa hamley +2 gardaa pani

In [13]:
#power ko lagi
x = np.array([5,4,6,1])
xpower = x **2
print(xpower)

[25 16 36  1]


In [14]:
x = np.array([5,4,6,1])
xpower = np.power(x,2)
print(xpower)

[25 16 36  1]


In [16]:
x = np.array([5,4,6,1])
z = np.add(x,2) #z = x+2

#code ma kasari kaam garcha?
#[5,4,6,1]+[2,2,2,2]
print(z)

[7 6 8 3]


In [ ]:
#task
x = np.array([5,6,2,7])
#kehi element add garnaa parey k garne?


In [22]:
#1.[5,6,2,7,9]
#2.[5,9,6,2,7]
#yesto chaiyooo

x = np.array([5,6,2,7])
x = np.append(x,9)
#append=> add at the end 

print(x)

[5 6 2 7 9]


In [25]:
x = np.array([5,6,2,7])
#insert : syntax np.insert(array, where to insert, value to be inserted)
x =np.insert(x,1,9)
print(x)

[5 9 6 2 7]


In [4]:
#Reshaping
print(x.shape)

(4,)


In [5]:
#reshaping
x.reshape(2,2)

array([[5, 4],
       [6, 1]])

In [6]:
#reshaping
x.reshape(2,3)
#mathi 4 ottaaa element cha aaba 2,2, ko matrix banauna ta sakenchha but 2,3 ko matarix banauna sakedena tesko lagi 
6 otaaa element chaihencha

ValueError: cannot reshape array of size 4 into shape (2,3)

In [7]:
a = np.array([4,6,2,7,9,12])
print(a.shape)

(6,)


In [8]:
# yehaaa reshape garna ko lagi kun kun banchhaa vanda
# (3,2)
# (2,3)
# (1,6)
# (6,1)

In [9]:
print(a.reshape(1,6)) #row matrix
#yo ra muthi koma farak cha kinaki yo 1 dimension ko ho bhane mathi ko multi

[[ 4  6  2  7  9 12]]


In [10]:
print(a.reshape(6,1)) #column matrix

[[ 4]
 [ 6]
 [ 2]
 [ 7]
 [ 9]
 [12]]


In [11]:
# numpy use gaeraa random number generate garna ko lagi yo function use hunchhaa
# #numpy array bandenchha

In [ ]:
### -np.zeros()
### -np.ones()
### -np.full()
### -np.arrange()
### -np.linspace()
-np.random.random()
-np.random.randint()
-np.random.uniform()

In [12]:
x = np.zeros(5) #sabei 0 element vako number generate vaidenchhaa
print(x)

[0. 0. 0. 0. 0.]


In [27]:
x = np.zeros((2,5))# 2 rows 5 columns
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [28]:
#another way
x = np.zeros(10).reshape(2,5)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [29]:
y = np.ones(5)
print(y)

[1. 1. 1. 1. 1.]


In [31]:
y = np.ones((2,5))# 2 rows 5 columns
print(y)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [35]:
#np.full()
#=> vitraa ko element lai repeat gardenchha
z = np.full(7, 5)# 7 choti 5 vanne element lai print garaideney
print(z)

[5 5 5 5 5 5 5]


In [37]:
z = np.full((2,3),7)#2 row 3 column and the element is 7
print(z)

[[7 7 7]
 [7 7 7]]


In [40]:
#np.arrange()
#np.linspace()

#range(start index, stop index, step)
#=> arrange range sanga similar cha

x = np.arange(2,10,2) #arrange ko syntax : np.arrange(start,stop,step)
print(x)

[2 4 6 8]


In [41]:

x = np.arange(2,10,2).reshape(2,2) 
print(x)

[[2 4]
 [6 8]]


In [42]:
#linsapce
 #linspace lo syntax: np.linspace(start,stop, how many numbers?)
x=np.linspace(1,10,5)
print(x)

[ 1.    3.25  5.5   7.75 10.  ]


In [44]:
x = np.linspace(1,10,15) # 15 ottaa number generate hune vo start from 1 and end to 10
print(x)

[ 1.          1.64285714  2.28571429  2.92857143  3.57142857  4.21428571
  4.85714286  5.5         6.14285714  6.78571429  7.42857143  8.07142857
  8.71428571  9.35714286 10.        ]


In [45]:
#np.random.random()
# => random number generate gardencha between 0 to 1
x = np.random.random(6)
#geneartes random number between 0 -1
print(x)

[0.1662038  0.14035899 0.11846626 0.1554851  0.98811067 0.24663689]


In [46]:
x = np.random.random((5,2))# 5 rows 2 columns
print(x)

[[0.52552826 0.22977629]
 [0.77938849 0.49852419]
 [0.23244782 0.15426076]
 [0.9821475  0.95906098]
 [0.58699154 0.41408822]]


In [47]:
#np.random.randint()
#=> randomly number generate hunchhaa

y=np.random.randint(0,10,5) # o to 10 sammaa ko number 5 otaaa randomly generate gardenchha
print(y)

[4 6 6 2 2]


In [48]:
y=np.random.randint(0,100,15)
print(y)

[25  8 14 54 16 31 83 68 50 16 84 84 62 91  0]


In [52]:
y=np.random.randint(0,10000,1105) #range badi vako vayeraa deyena
print(y)

[2468 5030 4960 ... 3641 8748 1560]


In [49]:
#yemsaa 2 dimension chaiyee reshape garnu parchhaa

In [50]:
#random.uniform()
# => floating point haru generate gardchhaa randomly
z = np.random.uniform(0,10,5)
print(z)

[0.77974674 2.06958265 2.47255811 2.87790139 1.30886532]


### Pandas

### pandas
### =>tabular format ma hunchhaa dataa, model fit gardaa.
### => so pandas ley row,column ko data operate garnaa sakchhaa
### datastructure of pandas. 1) series
###                          2) DataFrame

In [53]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.


In [54]:
import pandas as pd


### Series

In [57]:
x = pd.Series([5,7,8,9,2])
print(x)

0    5
1    7
2    8
3    9
4    2
dtype: int64


In [59]:
x = pd.Series([5,7,8,9,2],index=['a','b','c','d','e'])#aafei index pani dena melchha series ma
print(x)

a    5
b    7
c    8
d    9
e    2
dtype: int64


In [60]:
#range ma ni denaa melchhaaa index lai


x = pd.Series([5, 7, 8, 9, 2], index=range(100, 105))
print(x)


100    5
101    7
102    8
103    9
104    2
dtype: int64


In [58]:
x[2] 

np.int64(8)

In [ ]:
#task
1) loc
2) iloc()
hint: index aafei define pani garnaa sakenchhaa series ma 