In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn

In [38]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error , mean_absolute_percentage_error, r2_score

In [5]:
df =pd.read_csv('Salary Data.csv')

In [6]:
df

Age  Gender Education Level                      Job Title  \
0    32.0    Male      Bachelor's              Software Engineer   
1    28.0  Female        Master's                   Data Analyst   
2    45.0    Male             PhD                 Senior Manager   
3    36.0  Female      Bachelor's                Sales Associate   
4    52.0    Male        Master's                       Director   
..    ...     ...             ...                            ...   
370  35.0  Female      Bachelor's       Senior Marketing Analyst   
371  43.0    Male        Master's         Director of Operations   
372  29.0  Female      Bachelor's         Junior Project Manager   
373  34.0    Male      Bachelor's  Senior Operations Coordinator   
374  44.0  Female             PhD        Senior Business Analyst   

     Years of Experience    Salary  
0                    5.0   90000.0  
1                    3.0   65000.0  
2                   15.0  150000.0  
3                    7.0   60000.0  
4                   20.0  200000.0  
..                   ...       ...  
370                  8.0   85000.0  
371                 19.0  170000.0  
372                  2.0   40000.0  
373                  7.0   90000.0  
374                 15.0  150000.0  

[375 rows x 6 columns]

In [15]:
x = df[['Age']]
x.head()

Age
0  32.0
1  28.0
2  45.0
3  36.0
4  52.0

In [16]:
y = df[['Salary']]
y

Salary
0     90000.0
1     65000.0
2    150000.0
3     60000.0
4    200000.0
..        ...
370   85000.0
371  170000.0
372   40000.0
373   90000.0
374  150000.0

[373 rows x 1 columns]

In [17]:
linear_model = LinearRegression()
linear_model.fit(x,y)

LinearRegression()

In [11]:
df.isnull().sum()
df.dropna(inplace = True)

In [12]:
df.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [18]:
linear_model.intercept_

array([-135021.17727347])

In [19]:
linear_model.coef_

array([[6294.10178506]])

In [21]:
agenew = 45
linear_model.predict([[agenew]])

C:\Users\LENOVO\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[148213.40305422]])

In [22]:
#mean square nekalna ko lagiii


### Mean square Error 

In [23]:
ypred = linear_model.predict(x)

In [ ]:
x    -y    ypred

In [24]:
x.head()

Age
0  32.0
1  28.0
2  45.0
3  36.0
4  52.0

In [25]:
y


Salary
0     90000.0
1     65000.0
2    150000.0
3     60000.0
4    200000.0
..        ...
370   85000.0
371  170000.0
372   40000.0
373   90000.0
374  150000.0

[373 rows x 1 columns]

In [26]:
ypred

array([[ 66390.07984844],
       [ 41213.6727082 ],
       [148213.40305422],
       [ 91566.48698868],
       [192272.11554964],
       [ 47507.77449326],
       [129331.09769904],
       [ 60095.97806338],
       [ 28625.46913809],
       [104154.6905588 ],
       [ 47507.77449326],
       [167095.7084094 ],
       [ 85272.38520362],
       [116742.89412892],
       [ 34919.57092314],
       [141919.30126916],
       [ 72684.1816335 ],
       [110448.79234386],
       [ 22331.36735303],
       [185978.01376458],
       [ 78978.28341856],
       [160801.60662434],
       [ 53801.87627832],
       [ 91566.48698868],
       [123036.99591398],
       [ 41213.6727082 ],
       [ 97860.58877374],
       [ 16037.26556797],
       [135625.1994841 ],
       [ 72684.1816335 ],
       [179683.91197952],
       [ 60095.97806338],
       [ 47507.77449326],
       [110448.79234386],
       [154507.50483928],
       [ 34919.57092314],
       [ 85272.38520362],
       [129331.09769904],
       [ 286

In [27]:
error = y - ypred
error

Salary
0    23609.920152
1    23786.327292
2     1786.596946
3   -31566.486989
4     7727.884450
..            ...
370   -272.385204
371  34374.800516
372  -7507.774493
373  11021.716581
374   8080.698731

[373 rows x 1 columns]

In [31]:
error2 = np.power(error, 2)


In [32]:
error2

Salary
0    5.574283e+08
1    5.657894e+08
2    3.191929e+06
3    9.964431e+08
4    5.972020e+07
..            ...
370  7.419370e+04
371  1.181627e+09
372  5.636668e+07
373  1.214782e+08
374  6.529769e+07

[373 rows x 1 columns]

In [33]:
mse = np.mean(error2)

In [35]:
print(f'MSE:{mse:.2f}')

MSE:346499059.42


In [36]:
#or

mse = np.mean(np.power(error,2))

In [ ]:
portion of variance of depenedent variable , explained by independent variable => r2 square 
independent variable ley dependent variable lai kati explain garnaa sakerachhaa

In [39]:
#syntax: mean_square-error(yactual,ypredicated)


In [ ]:
y actual : y ma chhaa
y predicted : ypred ma chhaa

In [41]:
#mean swuare error
mse = mean_squared_error(y,ypred)
print(f'MSE:{mse:.2f}')

MSE:346499059.42


In [ ]:
RMSE ko lagi direct function chhaina so 
mse ko square root  garnaa saknecha

In [42]:
#root mean square error
rmse = np.sqrt(mse)
print(f'RMSE:{rmse:.2f}')

RMSE:18614.49


In [43]:
#mean absolute error
mae = mean_absolute_error(y,ypred)
print(f'MAE:{mae:.2f}')

MAE:13960.57


In [46]:
#mean absolute percentage error
mape = mean_absolute_percentage_error(y,ypred)
mape=mape*100
print(f'MAPE:{mape:.2f}%')

MAPE:52.47%


In [47]:
#R2 square
r2 = r2_score(y,ypred)
print(f'R2_score:{r2:.2f}')

R2_score:0.85


In [ ]:
Model train gareyo
x value deyeraa predct gareyo
tehaa bataa y ra ypred nekaleyo

aaba now testing garnee

In [ ]:
Testing gardaa training gareko data deyeraa test garedenaa

-> Testing:: don't give the data of training


In [ ]:
total data lai 2 part ma divide garenchhaa
1) training data
2) testing data


eg : hami snaga 100 rose chhaa vaney 
        80 ottaa training data ma pass agrne
        20 ottaa tesing ma pass garaunee
=> x_train , y_train    : training data


=> training dtaa abataa pattern bujnee but test gardaa aru data test garne
=> dhreie data training ma pathainchhaa , kam data testing ma 

-> testing:: x_test , y_test

In [ ]:
Data
   x , y
   xtrain,xtest           ytrain , ytest       

In [ ]:
train_test_split

In [58]:
from sklearn.model_selection import train_test_split

In [50]:
data = pd.read_csv('Salary Data.csv')
data.head()

Age  Gender Education Level          Job Title  Years of Experience  \
0  32.0    Male      Bachelor's  Software Engineer                  5.0   
1  28.0  Female        Master's       Data Analyst                  3.0   
2  45.0    Male             PhD     Senior Manager                 15.0   
3  36.0  Female      Bachelor's    Sales Associate                  7.0   
4  52.0    Male        Master's           Director                 20.0   

     Salary  
0   90000.0  
1   65000.0  
2  150000.0  
3   60000.0  
4  200000.0

In [51]:
data.isnull().sum()


Age                    2
Gender                 2
Education Level        2
Job Title              2
Years of Experience    2
Salary                 2
dtype: int64

In [52]:
data.dropna(inplace = True)

In [53]:
data.isnull().sum()

Age                    0
Gender                 0
Education Level        0
Job Title              0
Years of Experience    0
Salary                 0
dtype: int64

In [55]:
#create X and y
x = data[['Age']]
y =data.Salary



In [56]:
x

Age
0    32.0
1    28.0
2    45.0
3    36.0
4    52.0
..    ...
370  35.0
371  43.0
372  29.0
373  34.0
374  44.0

[373 rows x 1 columns]

In [57]:
y

0       90000.0
1       65000.0
2      150000.0
3       60000.0
4      200000.0
         ...   
370     85000.0
371    170000.0
372     40000.0
373     90000.0
374    150000.0
Name: Salary, Length: 373, dtype: float64

In [59]:
#split to train and test
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2)

In [60]:
xtrain

Age
142  33.0
347  45.0
156  32.0
354  31.0
91   29.0
..    ...
374  44.0
177  31.0
99   45.0
225  40.0
186  33.0

[298 rows x 1 columns]

In [61]:
ytrain

142     50000.0
347    180000.0
156     50000.0
354     50000.0
91      40000.0
         ...   
374    150000.0
177     50000.0
99     110000.0
225    105000.0
186     95000.0
Name: Salary, Length: 298, dtype: float64

aaba yo xtest ra ytrain feri run gardaaa data aarko split ma run hunchhaa so yesto nahuna lai we use :  ### random_state 

In [62]:
#split to train and test
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = 0.2, random_state = 19)

In [63]:
xtrain

Age
211  45.0
243  46.0
257  35.0
49   25.0
65   38.0
..    ...
19   51.0
356  45.0
246  49.0
110  42.0
93   52.0

[298 rows x 1 columns]

In [64]:
ytrain


211    150000.0
243    150000.0
257     95000.0
49      35000.0
65      90000.0
         ...   
19     180000.0
356    160000.0
246    180000.0
110    110000.0
93     170000.0
Name: Salary, Length: 298, dtype: float64

In [ ]:
aaba feri jati patak xtrain ra ytrain lai run gardaa pani value changeee gardennaaa

In [65]:
xtrain


Age
211  45.0
243  46.0
257  35.0
49   25.0
65   38.0
..    ...
19   51.0
356  45.0
246  49.0
110  42.0
93   52.0

[298 rows x 1 columns]

In [66]:
model = LinearRegression() # aaba purei x ra y deney hainaa fit garnaaa we use xtrain and ytrain
model.fit(xtrain,ytrain)

LinearRegression()

In [69]:
xtest

Age
319  37.0
210  38.0
176  42.0
129  34.0
143  47.0
..    ...
316  34.0
149  45.0
284  35.0
226  46.0
282  47.0

[75 rows x 1 columns]

In [70]:
ytest

319    120000.0
210    110000.0
176    140000.0
129    105000.0
143    135000.0
         ...   
316     80000.0
149    175000.0
284    100000.0
226    160000.0
282    170000.0
Name: Salary, Length: 75, dtype: float64

In [ ]:
#Evaluation
xtest       ytest        ypredction 

In [74]:
yprediction = model.predict(xtest)

In [75]:
yprediction


array([ 98038.38277426, 104417.08576233, 129931.89771461,  78902.27381005,
       161825.41265495, 149068.00667881, 129931.89771461, 117174.49173847,
       110795.7887504 , 117174.49173847, 180961.52161916, 104417.08576233,
       104417.08576233,  91659.67978619,  53387.46185778,  91659.67978619,
       187340.22460723, 180961.52161916, 136310.60070268,  40630.05588164,
       142689.30369074,  98038.38277426, 104417.08576233, 168204.11564302,
        27872.6499055 ,  85280.97679812, 104417.08576233,  47008.75886971,
       168204.11564302,  59766.16484585,  47008.75886971, 129931.89771461,
        40630.05588164,  72523.57082199, 136310.60070268,  53387.46185778,
        47008.75886971,  91659.67978619,  72523.57082199, 149068.00667881,
       161825.41265495, 110795.7887504 ,  27872.6499055 ,  72523.57082199,
        47008.75886971,  85280.97679812,  59766.16484585,  34251.35289357,
        15115.24392936, 149068.00667881,  47008.75886971,  72523.57082199,
        91659.67978619,  

In [ ]:
xtest         ytest        ypredction


In [76]:
mae = mean_absolute_error(ytest,yprediction)
print(f'MAE:{mae:.2f}')

MAE:13236.09


In [ ]:
   hamro flow 

1) x,y
2) xtrain,xtest,ytrain,ytest
3) model.fit(xtrain,ytrain)
4) ypredcition=model.predict(xtest)
5) mean _absolute_error(ytest,ypredcition)

In [ ]:
assignment : x = age, years of experience 